version: "1"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: pinflag_challenge
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"

  db-test:
    image: postgres
    environment:
      POSTGRES_DB: pinflag_challenge
      POSTGRES_PASSWORD: docker
    ports:
      - "5430:5432"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - db-test
    environment:
      DATABASE_URL: postgres://postgres:docker@db:5432/pinflag_challenge
